### PR TITLE
Cast initMethod return to fix compiler error to fix #2

### LINKED ISSUE #2: MockInject fails to build with CocoaPods 0.36.
MI 1.0.2 fails to build under CocoaPods 0.36 with the following error: 

```
/Pods/MockInject/MockInject/MIMocker.m:22:21: error: too many arguments to function call, expected 0, have 2
    return superImp(self,_cmd);
```

From the difference in the build commands in Xcode, the only thing I can see that may be relevant is the addition of the  -DOBJC_OLD_DISPATCH_PROTOTYPES=0 flag by pods 0.36.

I'll have a PR for this build issue momentarily but I don't know if it's the correct fix.

### PR DESCRIPTION
**Pull request by jshier**
Fixes #2

### CODE REVIEW

**Comment by jshier** [comment]
@gantaa Any chance of this getting landed?

**Comment by gantaa** [comment]
Yes,  I will test this today and get the PodSpec updated after verifying it.  Thanks for the help!
