### ISSUE TITLE
MockInject fails to build with CocoaPods 0.36.

### ISSUE THREAD

**Issue by jshier** [gantaa/MockInject#2]
MI 1.0.2 fails to build under CocoaPods 0.36 with the following error: 

```
/Pods/MockInject/MockInject/MIMocker.m:22:21: error: too many arguments to function call, expected 0, have 2
    return superImp(self,_cmd);
```

From the difference in the build commands in Xcode, the only thing I can see that may be relevant is the addition of the  -DOBJC_OLD_DISPATCH_PROTOTYPES=0 flag by pods 0.36.

I'll have a PR for this build issue momentarily but I don't know if it's the correct fix.

**Comment by gantaa** [comment]
New version is 1.0.3 and now available in the Pods master repo.  Thanks again.  Sorry, I had notifications turned off and wasn't notified of your original issue creation.  Notifications are now turned on for any further problems you might have

**Comment by jshier** [comment]
I see it, thanks a lot.
